#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : oslotest
Version  : 3.6.0
Release  : 46
URL      : http://tarballs.openstack.org/oslotest/oslotest-3.6.0.tar.gz
Source0  : http://tarballs.openstack.org/oslotest/oslotest-3.6.0.tar.gz
Source99 : http://tarballs.openstack.org/oslotest/oslotest-3.6.0.tar.gz.asc
Summary  : Oslo test framework
Group    : Development/Tools
License  : Apache-2.0
Requires: oslotest-bin
Requires: oslotest-python3
Requires: oslotest-license
Requires: oslotest-python
Requires: debtcollector
Requires: fixtures
Requires: mox3
Requires: os-client-config
Requires: python-mock
Requires: python-subunit
Requires: six
Requires: testtools
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Team and repository tags
        ========================

%package bin
Summary: bin components for the oslotest package.
Group: Binaries
Requires: oslotest-license

%description bin
bin components for the oslotest package.


%package license
Summary: license components for the oslotest package.
Group: Default

%description license
license components for the oslotest package.


%package python
Summary: python components for the oslotest package.
Group: Default
Requires: oslotest-python3

%description python
python components for the oslotest package.


%package python3
Summary: python3 components for the oslotest package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oslotest package.


%prep
%setup -q -n oslotest-3.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532269860
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/oslotest
cp LICENSE %{buildroot}/usr/share/doc/oslotest/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/oslo_debug_helper
/usr/bin/oslo_run_cross_tests
/usr/bin/oslo_run_pre_release_tests

%files license
%defattr(-,root,root,-)
/usr/share/doc/oslotest/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
